# ================================
# APPLICATION
# ================================
spring.application.name=events
server.port=9091
server.servlet.context-path=/Events

# ================================
# EUREKA CLIENT
# ================================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true

# ================================
# BASE DE DONNÉES
# ================================
spring.datasource.url=jdbc:mysql://localhost:3306/events_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

# ================================
# JPA / HIBERNATE
# ================================
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.jdbc.batch_size=50

# ================================
# UPLOAD FICHIERS
# ================================
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

# ================================
# EMAIL
# ================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=nour.mahmoud@esprit.tn
spring.mail.password=qvaufxzmxsqzletv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.mail.admin=nouurrmahmoudd@gmail.com

# ================================
# API KEYS
# ================================
anthropic.api.key=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
groq.api.key=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

# ================================
# GATEWAY CORS
# ================================
spring.cloud.gateway.globalcors.add-to-simple-url-handler-mapping=true