spring.application.name=nephro-forum
spring.cloud.config.enabled=true
spring.config.import=optional:configserver:http://localhost:8888

#config
management.endpoints.web.exposure.include=health, info, refresh