# APPLICATION — nom tel qu'il apparaît dans Eureka
spring.application.name=CAR
server.port=8077
# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
# ACTUATOR (health pour Eureka)
management.endpoints.web.exposure.include=health,info
