# APPLICATION
spring.application.name=consultation-microservice
server.port=8089
# EUREKA CLIENT
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=true
# BASE DE DONNÉES
spring.datasource.url=jdbc:mysql://localhost:3306/consultation_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# EMAIL
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=pedianephro1@gmail.com
spring.mail.password=vwnqinveqlabwbhi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true